FROM opensuse/leap

LABEL maintainer="Michael Adam <obnox@samba.org>"

ARG BUILD_LANG=""
ARG INSTALL_SCRIPT=""
ARG VERIFY_SCRIPT=""

LABEL org.opencontainers.image.title="${BUILD_LANG}  Build Container"
LABEL org.opencontainers.image.description="OpenSUSE Container for building ${BUILD_LANG} projects"
LABEL org.opencontainers.image.vendor="buildbox"
LABEL org.opencontainers.image.url="https://github.com/TheBuildBox/buildbox"



COPY "${VERIFY_SCRIPT}" /usr/local/bin/verify.sh
COPY common.sh /usr/local/bin/common.sh
RUN chmod +x /usr/local/bin/verify.sh
COPY  "${INSTALL_SCRIPT}" /usr/local/bin/install-packages.sh
RUN chmod +x /usr/local/bin/install-packages.sh
ENV PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin
# install, fix, and verify in ONE ATOMIC STEP,
# forcing a sane PATH for the duration of the install
RUN true && \
export PATH="/usr/local/bin:/usr/bin:/bin:/sbin:/usr/local/sbin:/usr/sbin" && \
/usr/local/bin/install-packages.sh && \
echo "Restoring symlinks if broken..." && \
( [ -L /bin ] || (mv /bin/* /usr/bin/ && rm -rf /bin && ln -s usr/bin /bin) ) && \
echo "Verifying binaries before layer commit..." && \
/usr/local/bin/verify.sh && \
echo "your buildbox is ready."

