name: build buildbox images

on:
  push:
    tags:
      - v*
    branches:
      - main
      - release-* 
  pull_request:

    branches:
      - main
      - release-*

# cancel the in-progress workflow when PR is refreshed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read


jobs:
  ImageBuild:
    strategy:
      matrix:
        os: [fedora, suse, debian, ubuntu]
        lang: [c,latex]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the container image
        run: |
          make CONTAINER_CMD=docker IMAGE_OS=${{ matrix.os}} IMAGE_LANG=${{ matrix.lang}} image-build
